### ISSUE TITLE
Error occured when run train_RPP.sh

### ISSUE THREAD

**Issue by huo123lijuan** [syfafterzy/PCB_RPP#12]
Traceback (most recent call last):
  File "RPP.py", line 226, in <module>
    main(parser.parse_args())
  File "RPP.py", line 166, in main
    checkpoint = load_checkpoint(osp.join(args.logs_dir, 'checkpoint.pth.tar'))
  File "/home/uers/PCB_RPP_for_reID-master/reid/utils/serialization.py", line 37, in load_checkpoint
    raise ValueError("=> No checkpoint found at '{}'".format(fpath))
ValueError: => No checkpoint found at 'logs/market-1501/RPP/checkpoint.pth.tar'

**Comment by xinshou-xiaobai** [comment]
I also met this problem. Do you fix it? If it was solved, please tell me the method.
